#!/bin/sh

TODAY=`date +"%Y-%m-%d"`
YESTERDAY=`date --date='yesterday' +"%Y-%m-%d"`
TWOMONTHSAGO=`date --date='2 months ago' +"%Y-%m-%dT00:00:00-0000"`
TWOMONTHSAGO_FRIENDLY=`echo $TWOMONTHSAGO | sed -r 's/^(.*?)T00:00:00-0000$/\1/'`
PARITYCHECKINPROGRESS=`cat /proc/mdcmd | grep "mdResync=1"`

# reference surlatablo call that might come in handy commented out here.
# /config/scripts/surlatablo.py --convert --ccaption --query lair_date~="$TODAY|$YESTERDAY" 

# copy surlatablo configuration to the location the python script expects
# since surlatablo-2.0b1-py, config was renamed to surlatablo2.conf
cp -u /config/conf/surlatablo2.conf /root/surlatablo2.conf

if [ ! $PARITYCHECKINPROGRESS ]; then

    # Process TV series first, and we only grab them if they aired yesterday or today.
    # Leave the commercials since fast forward with thumbnails works really well on the roku,
    # and I do not expect to be keeping these files after they have been watched.
    # Also, extract SRT files for closed captioning.
    /config/scripts/surlatablo.py --query lair_date~="($TODAY|$YESTERDAY)" | awk '{ if ($3 == "TV") system ("/config/scripts/surlatablo.py --convert --ccaption --query rec_id~=" $1); }' > /dev/null

    # Process Movies next, and again, we only grab them if they aired yesterday or today.
    # Try and zap commercials since these files will probably be kept even after they have
    # been watched.  We do not keep subtitles because that features is not working with
    # zapped commercial output.
    /config/scripts/surlatablo.py --query lair_date~="($TODAY|$YESTERDAY)" | awk '{ if ($3 == "Movie") system ("/config/scripts/surlatablo.py --convert -z --query rec_id~=" $1 " Mp4z"); }' > /dev/null

    # Experimental:  delete out unprotected `TV` recordings that are older than our configured `OLD` date.
    printf "\nWorking on deleting the following TV recordings because they were recorded before $TWOMONTHSAGO_FRIENDLY:\n"
    /config/scripts/surlatablo.py --query " " | awk -v OLD=$TWOMONTHSAGO '{ if ($2 < OLD && $3 == "TV") system ("/config/scripts/surlatablo.py --convert -P --query rec_id~=" $1 " DeleteX"); }'
    printf "\n"

    # These remaining recordings are candidates for deletion, but we only auto delete `TV` recordings.
    printf "\nThese remaining recordings are also old (recorded before $TWOMONTHSAGO_FRIENDLY), but only TV recordings are auto deleted so these will need to be manually reviewed:\n"
    /config/scripts/surlatablo.py --query " " | awk -v OLD=$TWOMONTHSAGO '{ if ($2 < OLD && $3 != "TV") print $0; }'
    printf "\n"

fi
exit 0
