#!/usr/bin/with-contenv bash


#######################################
#
# The SurLaTablo python project may be nearing end of support:
#  The hosting website (http://endlessnow.com/ten/SurLaTablo/)
#  has expired security certificates and the script has been v2.3
#  for a couple years now.
#
#######################################

sVERSION=surlatablo-2.3-py.txt

dSCRIPTS=/config/scripts/
dCONF=/config/conf/
mkdir -p $dSCRIPTS $dCONF

# Default config files mapped over to external volumes so they can be accessed outside of the container
cp /defaults/config/conf/surlatablo2.conf /config/conf/surlatablo2.conf
cp /defaults/config/scripts/cpFromTablo.py /config/scripts/cpFromTablo.py
cp /defaults/config/scripts/$sVERSION /config/scripts/surlatablo.py
chmod +x /config/scripts/surlatablo.py

# Handle passing in IP address of a single Tablo as container variable
if [ -n "$TABLO_IP" ]; then 
    sed -i "s/^TABLO_IPS = .*?/TABLO_IPS = ['$TABLO_IP']/g" /config/conf/surlatablo2.conf
fi

# symbolic link configuration file to where the surlatablo script expects it
ln -sf /config/conf/surlatablo2.conf /root/surlatablo2.conf

exit 0
