name: Push Powershell-Scheduler Container

on:
  push:
    branches: [ "master" ]
    paths:
      - 'powershell-scheduler/**'
  workflow_dispatch: # Enables the manual "Run workflow" button in the GitHub UI

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Read Version
        id: version
        run: |
          VERSION=$(cat ./powershell-scheduler/VERSION)

          if [ -z "$VERSION" ]; then
            echo "ERROR: VERSION file is empty."
            exit 1
          fi

          echo "Building Powershell-Scheduler version $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Powershell-Scheduler
        uses: docker/build-push-action@v7
        with:
          context: ./powershell-scheduler
          push: true
          tags: |
            ccridge/powershell-scheduler:${{ steps.version.outputs.version }}
            ccridge/powershell-scheduler:latest
