name: Push Powershell-Scheduler Container Disable Globalization Invariant Mode Feature

on:
  push:
    branches: [ "feature/DisableGlobalizationInvariantMode" ]
    paths:
      - 'powershell-scheduler/**'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Powershell-Scheduler Feature
        uses: docker/build-push-action@v7
        with:
          context: ./powershell-scheduler
          push: true
          tags: |
            ccridge/powershell-scheduler:dgim
